LANDING_WORK_CAR_SUB_ADDRESS.sql >>
CREATE TABLE `LANDING.WORK_CAR_SUB_DELIVERY_OPTIONS`
(
ID STRING,
DELIVERY_DATE STRING,
TIME_FRAME_ID STRING,
TIME_FRAME_DISPLAY_NAME STRING,
ADDRESS_ID STRING,
IS_HOME_ADDRESS STRING,
DELIVERY_INSTRUCTIONS_ID STRING,
JOB_RUN_ID INT64
)





	
