CREATE TABLE `LANDING.WORK_CAR_SUB_ADDRESS`
(
ID STRING,
PUBLIC_ID STRING,
STREET_ADDRESS STRING,
STREET_ADDRESS2 STRING,
CITY STRING,
STATE STRING,
COUNTRY STRING,
ZIP_CODE STRING,
CREATED_ON STRING,
LAST_MODIFIED STRING,
JOB_RUN_ID INT64
)